id = "chanterelle"
name = "Chanterelle Theme"
version = "0.0.1"
schema_version = 1
authors = ["Steffen Haug <st@haug.codes>"]
description = "A dark theme inspired by the nordic forest."
repository = "https://github.com/steffenhaug/chanterelle-zed"
